// <auto-generated />
namespace RESS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FinalMigration100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalMigration100));
        
        string IMigrationMetadata.Id
        {
            get { return "202111162300032_FinalMigration100"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
